name: Brakeman

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a Brakeman vulnerability scanner
        uses: standardnotes/brakeman-action@v1.0.0
        with:
          options: "--color"